apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.0 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "250m"
        ports:
        - containerPort: 5432
        livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 3 # Número de segundos após o início do container para o liveness
            periodSeconds: 10 # Intervalo de tempo entre as verificações
            failureThreshold: 3 # Número de falhas pra considerar a aplicação não saudável
            successThreshold: 1 # Número de sucessos para zerar o failureThreshold (No liveness é 1)
            timeoutSeconds: 3 # Timeout da chamada
            terminationGracePeriodSeconds: 30
        envFrom:
        - secretRef:
            name: postgre-secret
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: db-vol
          mountPath: "/var/lib/postgresql/data"
          subPath: "pgdata"
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: postgre-pvc
---
# An ubuntu pod if you need any troubleshot
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ubuntu
#   namespace: postgre
# spec:
#   selector:
#     matchLabels:
#       app: ubuntu
#   template:
#     metadata:
#       labels:
#         app: ubuntu
#     spec:
#       containers:
#       - name: ubuntu
#         image: ubuntu:latest
#         args:
#           - sleep
#           - infinity
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
# ---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgre
spec:
  type: ClusterIP # Service exposed for the k8s cluster only. If you want to access externally, change to LoadBalancer
  selector:
    app: postgresql
  ports:
  - name: db-port
    protocol: TCP
    port: 5432
    targetPort: 5432
  