apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: postgre
type: Opaque
data:
  POSTGRES_PASSWORD: "UGcxMjM=" # o valor não pode ser em texto plano, mas sim em base64. para gerar rodar no terminal: echo -n "<VALOR>" | base64
  POSTGRES_USER: "bmV0Ym94"
  POSTGRES_DB: "bmV0Ym94"
  POSTGRES_HOST: "cG9zdGdyZXNxbA=="