apiVersion: v1
kind: Namespace 
metadata: 
  name: postgre
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc
  namespace: postgre
  labels:
    name: postgre-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage