name: Deploy
on: 
  # push:
  #   branches: ["main"]
  workflow_dispatch:
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Postgre deploy
      uses: Azure/k8s-deploy@v5
      with:
        namespace: postgre
        manifests: |
          ./postgre-basics.yaml
          ./postgre-deployment.yaml
    - name: Netbox deploy
      uses: Azure/k8s-deploy@v5
      with:
        namespace: netbox-k8s
        manifests: |
          ./netbox-basics.yaml
          ./netbox-startup-configmap.yaml
          ./netbox-deployment.yaml